import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
// import { usePathname } from 'next/navigation'
import Protected from "./components/Protected";

import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const pathname = usePathname()

  // const searchParams = new URLSearchParams(window?.location?.search);
  //   // const idFromUrl = searchParams.get('id');
  //   console.log('from layout',searchParams)
  // console.log("from layout",pathname)
  return (
    <html lang="en">
      <body className={inter.className}>
      <Toaster position="top-right"/>
        <div className="">
          <div className="w-full">
        <Navbar />
        {children}
          </div>
        </div>
      
        </body>
    </html>
  );
}
